config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'notes/index'
  post 'notes/search'
  resources :notes do
    collection do 
      get 'search'
    end
  end
  root to: "notes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user

  def self.search(search)
    if search != ""
      Note.where('title LIKE(?)', "%#{search}%")
    else
      Note.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth

  private

  def basic_auth
    authenticate_or_request_with_http_basic do | username, password |
      username == 'admin' && password == '2222'
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_note, only: [:show,:edit,:update,:destroy]

  def index
    @notes = Note.where(user_id: current_user).order("created_at DESC")
  end

  def show
  end

  def new 
    @note = Note.new
  end

  def update
    if @note.update(note_params)
      redirect_to root_path
    else
      render "edit"
    end
  end

  def create
    @note = Note.new(note_params)

    if @note.save
      redirect_to @note
    else
      render 'new'
    end
  end

  def edit 
  end

  def destroy 
    if @note.destroy
      redirect_to notes_path
    end
  end

  def search
    @notes = Note.search(params[:search])
  end

  private

  def find_note
    @note = Note.find(params[:id])
  end

  def note_params 
    params.require(:note).permit(:title, :content).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.haml
!!!
%html 
%head
  %title Relist
  = stylesheet_link_tag 'application', media: 'all'
  = javascript_pack_tag 'application'
  = csrf_meta_tags
  = csp_meta_tag
%body
  %header
    .header_inner
      = link_to "Relist", root_path, class: "header_color"
      %nav
        - if user_signed_in?
          = link_to "＋", new_note_path
          = link_to "ログアウト", destroy_user_session_path, method: :delete
        - else 
          = link_to "ログイン", new_user_session_path
  = yield

app/views/notes/_form.html.haml
= simple_form_for @note do |f|
  =f.input :title, label: false, placeholder: "title", :input_html => { :class => 'title_width' }, local: true
  =f.input :content, label: false, placeholder: "text",:input_html => { :class => 'content_width' }, local: true
  =f.button :submit,  data: { disable_with: "送信中..."},class: 'button', local: true

app/views/notes/edit.html.haml
.wrapper_with_padding
    %h1 編集する
    = render 'form'
    = link_to "キャンセル", root_path

app/views/notes/index.html.haml
.wrapper_with_padding
  #notes
    - unless @notes.blank?
      = form_with(url: search_notes_path, local: true ) do |f|
        =f.text_field :search,  placeholder: "投稿を検索する", class: "search-input"
        =f.submit value: "検索", data: { disable_with: "送信中..."}, class: "button"

      - @notes.each do |note|
        %a.created_at{ href: (url_for [note])}
          .note
            %p.title= note.title
            %p.date= time_ago_in_words(note.created_at)
    - else 
      %h2 あなたが今思っていること、感じていることを書き出してみよう！
      %p - メリットや効果
      %p - 幸福感が高まり、頭が良くなる
      %p - 認知機能の向上
      %p - 嫌いな相手が気にならなくなる
      %p - 免疫力が向上する
      %p - 筆記開示の生みの親であるテキサス大学のジェームズ・ペネベーガー博士によると、「数々の研究により、エクスプレッシブ・ライティングを行った被験者は幸福感が高まり、ネガティブな感情が減った。さらには、数週間から数ヶ月でうつや不安が改善し、ストレスが穏やかになる傾向も見られた。」と述べられています。
      %button= link_to "新規投稿", new_note_path

app/views/notes/new.html.haml
.wrapper_with_padding
  %h1 新規投稿
  = render 'form'

app/views/notes/search.html.haml
.wrapper_with_padding
  #notes
    = form_with(url: search_notes_path, local: true ) do |f|
      =f.text_field :search,  placeholder: "投稿を検索する", class: "search-input"
      =f.submit value: "検索", data: { disable_with: "送信中..."}, class: "button"

    - @notes.each do |note|
      %a.created_at{ href: (url_for [note])}
        .note
          %p.title= note.title
          %p.date= time_ago_in_words(note.created_at)

app/views/notes/show.html.haml
.wrapper_with_padding 
  #note_show 
    %h1.title= @note.title 
    %P= @note.content

  .buttons 
    = link_to "編集する", edit_note_path(@note), class: "button"
    = link_to "削除する", note_path(@note), method: :delete, data: { confirm: "本当に削除してもよろしいですか？" }, class: "button"